# Generated by Django 5.1.7 on 2025-04-29 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия сотрудника')),
                ('photo', models.ImageField(upload_to='media/%y/%m/%d', verbose_name='Фото')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_residence', models.CharField(max_length=200, verbose_name='Адрес проживания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Запомнить')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Project.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Таблица сотрудников',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['id'],
            },
        ),
    ]
